[tool.poetry]
name = "course4"
version = "0.1.0"
description = ""
authors = ["AlexFreezeman <winterirk@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.30.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
